language: node_js
node_js:
  - '7.6.0'
  - '8'
  - '10'
  - '12'
  - 'node'
services:
  - mysql
install:
  - npm install
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS classicmodels;'
  - mysql -u root --default-character-set=utf8 classicmodels < tests/sample.sql
script:
  - npm test
