version: '3.5'

services:

  xdata-xmysql-service: 
    build:
      context: ./
      dockerfile: ./dev.Dockerfile
    environment:
      DATABASE_HOST: 'db'
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: 'pass'
      DATABASE_NAME: 'classicmodels'
    ports:
      - "3002:80"

